// frontend/mobile/src/App.vue
<template>
  <a-config-provider :locale="arcoLocale">
    <router-view />
  </a-config-provider>
</template>

<script setup lang="ts">
import { computed } from 'vue'

import zhCn from '@arco-design/web-vue/es/locale/lang/zh-cn'
import enUs from '@arco-design/web-vue/es/locale/lang/en-us'
import { useAppStore } from '@/stores/app'

const appStore = useAppStore()

const arcoLocale = computed(() => (appStore.locale === 'zh-CN' ? zhCn : enUs))
</script>

// frontend/portal/src/App.tsx
import { useEffect } from 'react'
import { ConfigProvider } from '@arco-design/web-react'
import enUS from '@arco-design/web-react/es/locale/en-US'
import zhCN from '@arco-design/web-react/es/locale/zh-CN'
import { RouterProvider } from 'react-router-dom'

import { router } from './router'
import { appStore, useAppStore } from './stores/app'
import { userStore } from './stores/user'

userStore.init()
appStore.init()

const ARCO_LOCALES = {
  'zh-CN': zhCN,
  'en-US': enUS,
} as const

export default function App() {
  const { locale, theme } = useAppStore()

  useEffect(() => {
    if (theme === 'dark') {
      document.body.setAttribute('arco-theme', 'dark')
    } else {
      document.body.removeAttribute('arco-theme')
    }
  }, [theme])

  return (
    <ConfigProvider locale={ARCO_LOCALES[locale]}>
      <RouterProvider router={router} />
    </ConfigProvider>
  )
}
